'use client'

import { useState } from 'react'
import { useRouter } from 'next/navigation'
import type { StoryTone, StoryLength } from '@/types/story'

const PRESETS = [
  'A climate-resilience adventure set in Kingston, Jamaica, where rising seas threaten an ancient port',
  'A young hacker in Lagos 2047 discovers an AI conspiracy inside the world\'s last mega-corporation',
  'Ancient Mayan astronomers must prevent a rogue planet collision using forgotten star maps',
]

const TONES: StoryTone[] = ['Epic', 'Whimsical', 'Thriller', 'Educational']
const LENGTHS: { label: string; value: StoryLength; desc: string }[] = [
  { label: 'Short', value: 'Short', desc: '3 scenes' },
  { label: 'Medium', value: 'Medium', desc: '5 scenes' },
  { label: 'Long', value: 'Long', desc: '8 scenes' },
]
const REGIONS = ['Caribbean', 'Africa', 'Global', 'South America', 'Southeast Asia', 'Custom']

export default function HomePage() {
  const router = useRouter()
  const [prompt, setPrompt] = useState('')
  const [tone, setTone] = useState<StoryTone>('Epic')
  const [length, setLength] = useState<StoryLength>('Short')
  const [region, setRegion] = useState('Caribbean')
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState('')

  async function handleCreate() {
    if (!prompt.trim()) {
      setError('Enter a story idea first.')
      return
    }
    setError('')
    setLoading(true)
    try {
      const res = await fetch('/api/story/generate', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ prompt: prompt.trim(), tone, region, length }),
      })
      const data = await res.json()
      if (!res.ok) throw new Error(data.error ?? 'Failed to start generation')
      router.push(`/generate?id=${data.id}`)
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Something went wrong')
      setLoading(false)
    }
  }

  return (
    <>
      {/* ── Hero ─────────────────────────────────────────────────────────── */}
      <section style={{ padding: '4rem 1.5rem 2rem', maxWidth: 1180, margin: '0 auto' }}>
        <div style={{ marginBottom: '3.5rem', textAlign: 'center' }}>
          <div
            style={{
              display: 'inline-flex',
              alignItems: 'center',
              gap: '0.5rem',
              fontSize: '0.75rem',
              fontWeight: 700,
              textTransform: 'uppercase',
              letterSpacing: '0.1em',
              padding: '0.35rem 0.9rem',
              borderRadius: 20,
              border: '1px solid rgba(102,126,234,0.35)',
              background: 'rgba(102,126,234,0.08)',
              color: '#667eea',
              marginBottom: '1.25rem',
            }}
          >
            <span style={{ width: 6, height: 6, borderRadius: '50%', background: '#667eea', display: 'inline-block' }} />
            Powered by Azure AI Foundry — Agents League 2026
          </div>
          <h1
            className="na-gradient-text"
            style={{ fontSize: 'clamp(2.2rem, 5vw, 3.4rem)', fontWeight: 800, lineHeight: 1.15, letterSpacing: '-0.03em', marginBottom: '1rem' }}
          >
            Turn Ideas Into Playable Stories
          </h1>
          <p style={{ fontSize: '1.1rem', color: 'var(--na-muted)', maxWidth: 560, margin: '0 auto', lineHeight: 1.7 }}>
            Fact-checked, multi-modal narratives generated by intelligent agents. Text, illustrations,
            audio narration, and a playable visual novel — from a single prompt.
          </p>
        </div>

        {/* ── Two-column layout ─────────────────────────────────────────── */}
        <div style={{ display: 'grid', gridTemplateColumns: '1fr 420px', gap: '2rem', alignItems: 'start' }}>

          {/* Left — Form */}
          <div className="na-card" style={{ padding: '2rem' }}>
            {/* Preset chips */}
            <div style={{ marginBottom: '1.25rem' }}>
              <p className="na-label">Story ideas — click to use</p>
              <div className="na-preset-chips">
                {PRESETS.map((p, i) => (
                  <button key={i} className="na-chip" onClick={() => setPrompt(p)} type="button">
                    {p.length > 55 ? p.slice(0, 55) + '...' : p}
                  </button>
                ))}
              </div>
            </div>

            {/* Prompt textarea */}
            <div style={{ marginBottom: '1.25rem' }}>
              <label className="na-label" htmlFor="prompt">Your story idea</label>
              <textarea
                id="prompt"
                className="na-textarea"
                rows={4}
                placeholder="A climate-resilience adventure set in Kingston, Jamaica..."
                value={prompt}
                onChange={e => setPrompt(e.target.value)}
              />
            </div>

            {/* Tone + Region row */}
            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '1rem', marginBottom: '1.25rem' }}>
              <div>
                <p className="na-label">Tone</p>
                <div className="na-pill-group">
                  {TONES.map(t => (
                    <button
                      key={t}
                      type="button"
                      className={`na-pill ${tone === t ? 'active' : ''}`}
                      onClick={() => setTone(t)}
                    >
                      {t}
                    </button>
                  ))}
                </div>
              </div>
              <div>
                <label className="na-label" htmlFor="region">Region / Setting</label>
                <select
                  id="region"
                  className="na-select"
                  value={region}
                  onChange={e => setRegion(e.target.value)}
                >
                  {REGIONS.map(r => (
                    <option key={r} value={r}>{r}</option>
                  ))}
                </select>
              </div>
            </div>

            {/* Length */}
            <div style={{ marginBottom: '1.75rem' }}>
              <p className="na-label">Story length</p>
              <div className="na-length-group">
                {LENGTHS.map(l => (
                  <button
                    key={l.value}
                    type="button"
                    className={`na-length-btn ${length === l.value ? 'active' : ''}`}
                    onClick={() => setLength(l.value)}
                  >
                    <strong>{l.label}</strong>
                    <br />
                    <span style={{ fontSize: '0.7rem', opacity: 0.7 }}>{l.desc}</span>
                  </button>
                ))}
              </div>
            </div>

            {error && (
              <div style={{ marginBottom: '1rem', padding: '0.7rem 1rem', borderRadius: 8, background: 'rgba(232,85,85,0.1)', border: '1px solid rgba(232,85,85,0.25)', color: '#e85555', fontSize: '0.85rem' }}>
                {error}
              </div>
            )}

            <button
              className="na-btn-primary"
              style={{ width: '100%', justifyContent: 'center', fontSize: '1.05rem', padding: '0.9rem' }}
              onClick={handleCreate}
              disabled={loading}
            >
              {loading ? <><span className="na-spinner" /> Launching agents...</> : 'Create Story'}
            </button>

            <p style={{ marginTop: '0.75rem', fontSize: '0.75rem', color: 'var(--na-muted)', textAlign: 'center' }}>
              PlotAgent + WorldAgent + MediaAgent + CodeAgent run in sequence
            </p>
          </div>

          {/* Right — Preview card */}
          <div>
            <p className="na-section-label" style={{ marginBottom: '0.75rem' }}>Sample output</p>
            <div className="na-preview-card">
              <div className="na-preview-image" style={{ minHeight: 160 }}>
                <div style={{
                  position: 'absolute', inset: 0,
                  background: 'linear-gradient(135deg, #0d1b4b 0%, #1a0a3c 35%, #0a2a40 100%)',
                  display: 'flex', alignItems: 'center', justifyContent: 'center'
                }}>
                  <div style={{ textAlign: 'center', opacity: 0.4 }}>
                    <div style={{ fontSize: '3rem', marginBottom: '0.5rem', lineHeight: 1 }}>&#9670;</div>
                    <div style={{ fontSize: '0.7rem', color: '#fff', letterSpacing: '0.1em', textTransform: 'uppercase' }}>AI-generated artwork</div>
                  </div>
                </div>
                <div className="na-preview-title" style={{ position: 'relative', zIndex: 2 }}>
                  Kingston&apos;s Last Stand
                </div>
              </div>
              <div className="na-preview-body">
                <div style={{ display: 'flex', gap: '0.35rem', flexWrap: 'wrap', marginBottom: '0.75rem' }}>
                  <span className="na-tag tone">Epic</span>
                  <span className="na-tag region">Caribbean</span>
                  <span className="na-tag length">5 Scenes</span>
                </div>
                <p className="na-preview-excerpt">
                  You stand at the edge of Kingston Harbour as the storm surge swells.
                  The old lighthouse blinks its final warning. Across the bay,
                  the evacuation sirens wail. Every second counts.
                </p>
                <div style={{ display: 'flex', gap: '0.5rem', flexWrap: 'wrap' }}>
                  <span style={{ fontSize: '0.75rem', color: 'var(--na-muted)' }}>Grounded by Foundry IQ:</span>
                  <span style={{ fontSize: '0.75rem', color: '#4caf91' }}>Hurricane Ivan (2004) data</span>
                </div>
                <div style={{ marginTop: '0.85rem', display: 'flex', flexDirection: 'column', gap: '0.4rem' }}>
                  {['Help evacuate the hospital', 'Secure the flood barriers'].map((c, i) => (
                    <div key={i} style={{
                      padding: '0.6rem 0.85rem',
                      borderRadius: 8,
                      border: '1px solid rgba(255,255,255,0.08)',
                      background: 'rgba(255,255,255,0.03)',
                      fontSize: '0.8rem',
                      color: 'var(--na-text)',
                      cursor: 'default'
                    }}>
                      {c}
                    </div>
                  ))}
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* ── How It Works ─────────────────────────────────────────────────── */}
      <section id="how-it-works" style={{ padding: '3rem 1.5rem 4rem', maxWidth: 1180, margin: '0 auto' }}>
        <hr className="na-divider" />
        <p className="na-section-label" style={{ textAlign: 'center', marginBottom: '2rem' }}>How it works</p>
        <div className="na-how-grid">
          {[
            {
              icon: '&#9998;',
              name: 'PlotAgent',
              desc: 'Queries Azure AI Search (Foundry IQ) for real facts, then crafts a story outline with branching scenes.',
            },
            {
              icon: '&#127758;',
              name: 'WorldAgent',
              desc: 'Expands each scene into vivid narrative text, camera-ready image prompts, and audio narration scripts.',
            },
            {
              icon: '&#9673;',
              name: 'MediaAgent',
              desc: 'Generates scene illustrations with GPT Image 2 and uploads them to Azure Blob Storage.',
            },
            {
              icon: '&#128195;',
              name: 'CodeAgent',
              desc: 'Assembles all assets into a final StoryBundle — a fully playable visual novel ready to share.',
            },
          ].map(step => (
            <div key={step.name} className="na-how-card">
              <div className="na-how-icon" dangerouslySetInnerHTML={{ __html: step.icon }} />
              <div className="na-how-name">{step.name}</div>
              <div className="na-how-desc">{step.desc}</div>
            </div>
          ))}
        </div>
      </section>
    </>
  )
}
